version: "3.3"
services:
  krakend:
    build: ../krakenD/
    container_name: "krakend"
    ports:
      - "9000:9000"
  spring-boot-local:
    build: ../
    container_name: "spring-boot-local"
    environment:
      SPRING_PROFILES_ACTIVE: default
  spring-boot-k8s-error:
    build: ../
    container_name: "spring-boot-k8s-error"
    environment:
      SPRING_PROFILES_ACTIVE: k8s-error
  spring-boot-k8s:
    build: ../
    container_name: "spring-boot-k8s"
    environment:
      SPRING_PROFILES_ACTIVE: k8s
